In [1]:
import pandas as pd

In [2]:
matches = pd.read_csv("spanish_matches.csv", index_col=0)

In [3]:
matches.head()

,date,time,comp,round,day,venue,result,gf,ga,opponent,...,match report,notes,sh,sot,dist,fk,pk,pkatt,season,team
0,2022-08-13,21:00,La Liga,Matchweek 1,Sat,Home,D,0.0,0.0,Rayo Vallecano,...,Match Report,NaN,21.0,5.0,17.0,1.0,0.0,0.0,2023,Barcelona
1,2022-08-21,22:00,La Liga,Matchweek 2,Sun,Away,W,4.0,1.0,Real Sociedad,...,Match Report,NaN,15.0,7.0,14.6,0.0,0.0,0.0,2023,Barcelona
2,2022-08-28,19:30,La Liga,Matchweek 3,Sun,Home,W,4.0,0.0,Valladolid,...,Match Report,NaN,24.0,9.0,14.4,1.0,0.0,0.0,2023,Barcelona
3,2022-09-03,21:00,La Liga,Matchweek 4,Sat,Away,W,3.0,0.0,Sevilla,...,Match Report,NaN,18.0,5.0,16.0,2.0,0.0,0.0,2023,Barcelona
5,2022-09-10,18:30,La Liga,Matchweek 5,Sat,Away,W,4.0,0.0,Cádiz,...,Match Report,NaN,16.0,8.0,14.9,0.0,0.0,0.0,2023,Barcelona

In [4]:
matches.shape

(2599, 27)

In [5]:
# Missing Liverpool 2021-2022
matches["team"].value_counts()

Real Sociedad      131
Atletico Madrid    131
Villarreal         131
Osasuna            131
Athletic Club      131
Sevilla            131
Getafe             131
Celta Vigo         131
Barcelona          130
Real Betis         130
Valencia           130
Real Madrid        130
Alaves             114
Levante            114
Granada            114
Cadiz               93
Espanyol            93
Valladolid          93
Mallorca            93
Elche               76
Eibar               76
Rayo Vallecano      55
Huesca              38
Leganes             38
Almeria             17
Girona              17
Name: team, dtype: int64

In [6]:
matches.shape

(2599, 27)

In [7]:
matches[matches["team"] == "Liverpool"].sort_values("date")

Empty DataFrame
Columns: [date, time, comp, round, day, venue, result, gf, ga, opponent, xg, xga, poss, attendance, captain, formation, referee, match report, notes, sh, sot, dist, fk, pk, pkatt, season, team]
Index: []

[0 rows x 27 columns]

In [8]:
matches["round"].value_counts()

Matchweek 1     79
Matchweek 10    79
Matchweek 2     79
Matchweek 16    79
Matchweek 15    79
Matchweek 13    79
Matchweek 12    79
Matchweek 11    79
Matchweek 14    79
Matchweek 9     79
Matchweek 7     79
Matchweek 6     79
Matchweek 5     79
Matchweek 4     79
Matchweek 8     79
Matchweek 3     79
Matchweek 17    75
Matchweek 33    60
Matchweek 30    60
Matchweek 31    60
Matchweek 32    60
Matchweek 36    60
Matchweek 34    60
Matchweek 35    60
Matchweek 37    60
Matchweek 28    60
Matchweek 29    60
Matchweek 19    60
Matchweek 27    60
Matchweek 26    60
Matchweek 25    60
Matchweek 24    60
Matchweek 23    60
Matchweek 22    60
Matchweek 20    60
Matchweek 21    60
Matchweek 18    60
Matchweek 38    60
Name: round, dtype: int64

In [9]:
matches.dtypes

date             object
time             object
comp             object
round            object
day              object
venue            object
result           object
gf              float64
ga              float64
opponent         object
xg              float64
xga             float64
poss            float64
attendance      float64
captain          object
formation        object
referee          object
match report     object
notes           float64
sh              float64
sot             float64
dist            float64
fk              float64
pk              float64
pkatt           float64
season            int64
team             object
dtype: object

In [10]:
del matches["comp"]

In [11]:
del matches["notes"]

In [12]:
matches["date"] = pd.to_datetime(matches["date"])

In [13]:
matches["target"] = (matches["result"] == "W").astype("int")

In [14]:
matches

,date,time,round,day,venue,result,gf,ga,opponent,xg,...,match report,sh,sot,dist,fk,pk,pkatt,season,team,target
0,2022-08-13,21:00,Matchweek 1,Sat,Home,D,0.0,0.0,Rayo Vallecano,1.9,...,Match Report,21.0,5.0,17.0,1.0,0.0,0.0,2023,Barcelona,0
1,2022-08-21,22:00,Matchweek 2,Sun,Away,W,4.0,1.0,Real Sociedad,2.1,...,Match Report,15.0,7.0,14.6,0.0,0.0,0.0,2023,Barcelona,1
2,2022-08-28,19:30,Matchweek 3,Sun,Home,W,4.0,0.0,Valladolid,2.6,...,Match Report,24.0,9.0,14.4,1.0,0.0,0.0,2023,Barcelona,1
3,2022-09-03,21:00,Matchweek 4,Sat,Away,W,3.0,0.0,Sevilla,4.0,...,Match Report,18.0,5.0,16.0,2.0,0.0,0.0,2023,Barcelona,1
5,2022-09-10,18:30,Matchweek 5,Sat,Away,W,4.0,0.0,Cádiz,3.4,...,Match Report,16.0,8.0,14.9,0.0,0.0,0.0,2023,Barcelona,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
50,2020-07-05,17:00,Matchweek 34,Sun,Home,L,0.0,1.0,Leganés,0.8,...,Match Report,7.0,2.0,18.9,1.0,0.0,0.0,2021,Espanyol,0
51,2020-07-08,22:00,Matchweek 35,Wed,Away,L,0.0,1.0,Barcelona,0.9,...,Match Report,11.0,2.0,18.1,1.0,0.0,0.0,2021,Espanyol,0
52,2020-07-12,14:00,Matchweek 36,Sun,Home,L,0.0,2.0,Eibar,0.7,...,Match Report,14.0,3.0,20.8,3.0,0.0,0.0,2021,Espanyol,0
53,2020-07-16,21:00,Matchweek 37,Thu,Away,L,0.0,1.0,Valencia,1.3,...,Match Report,18.0,6.0,21.3,3.0,0.0,0.0,2021,Espanyol,0
54,2020-07-19,21:00,Matchweek 38,Sun,Home,D,0.0,0.0,Celta Vigo,0.4,...,Match Report,8.0,1.0,17.2,0.0,0.0,0.0,2021,Espanyol,0

In [15]:
matches["venue_code"] = matches["venue"].astype("category").cat.codes

In [16]:
matches["opp_code"] = matches["opponent"].astype("category").cat.codes

In [17]:
matches["hour"] = matches["time"].str.replace(":.+", "", regex=True).astype("int")

In [18]:
matches["day_code"] = matches["date"].dt.dayofweek

In [19]:
matches

,date,time,round,day,venue,result,gf,ga,opponent,xg,...,fk,pk,pkatt,season,team,target,venue_code,opp_code,hour,day_code
0,2022-08-13,21:00,Matchweek 1,Sat,Home,D,0.0,0.0,Rayo Vallecano,1.9,...,1.0,0.0,0.0,2023,Barcelona,0,1,19,21,5
1,2022-08-21,22:00,Matchweek 2,Sun,Away,W,4.0,1.0,Real Sociedad,2.1,...,0.0,0.0,0.0,2023,Barcelona,1,0,21,22,6
2,2022-08-28,19:30,Matchweek 3,Sun,Home,W,4.0,0.0,Valladolid,2.6,...,1.0,0.0,0.0,2023,Barcelona,1,1,24,19,6
3,2022-09-03,21:00,Matchweek 4,Sat,Away,W,3.0,0.0,Sevilla,4.0,...,2.0,0.0,0.0,2023,Barcelona,1,0,22,21,5
5,2022-09-10,18:30,Matchweek 5,Sat,Away,W,4.0,0.0,Cádiz,3.4,...,0.0,0.0,0.0,2023,Barcelona,1,0,7,18,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
50,2020-07-05,17:00,Matchweek 34,Sun,Home,L,0.0,1.0,Leganés,0.8,...,1.0,0.0,0.0,2021,Espanyol,0,1,15,17,6
51,2020-07-08,22:00,Matchweek 35,Wed,Away,L,0.0,1.0,Barcelona,0.9,...,1.0,0.0,0.0,2021,Espanyol,0,0,4,22,2
52,2020-07-12,14:00,Matchweek 36,Sun,Home,L,0.0,2.0,Eibar,0.7,...,3.0,0.0,0.0,2021,Espanyol,0,1,8,14,6
53,2020-07-16,21:00,Matchweek 37,Thu,Away,L,0.0,1.0,Valencia,1.3,...,3.0,0.0,0.0,2021,Espanyol,0,0,23,21,3
54,2020-07-19,21:00,Matchweek 38,Sun,Home,D,0.0,0.0,Celta Vigo,0.4,...,0.0,0.0,0.0,2021,Espanyol,0,1,6,21,6

In [20]:
from sklearn.ensemble import RandomForestClassifier

In [21]:
rf = RandomForestClassifier(n_estimators=50, min_samples_split=10, random_state=1)

In [22]:
train = matches[matches["date"] < '2022-01-01']

In [23]:
test = matches[matches["date"] > '2022-01-01']

In [24]:
predictors = ["venue_code", "opp_code", "hour", "day_code"]

In [25]:
rf.fit(train[predictors], train["target"])

RandomForestClassifier(min_samples_split=10, n_estimators=50, random_state=1)

In [26]:
preds = rf.predict(test[predictors])

In [27]:
from sklearn.metrics import accuracy_score

In [28]:
error = accuracy_score(test["target"], preds)

In [29]:
error

0.6083916083916084

In [30]:
combined = pd.DataFrame(dict(actual=test["target"], predicted=preds))

In [31]:
pd.crosstab(index=combined["actual"], columns=combined["predicted"])

predicted    0    1
actual
0          339  105
1          175   96

In [32]:
from sklearn.metrics import precision_score

precision_score(test["target"], preds)

0.47761194029850745

In [33]:
grouped_matches = matches.groupby("team")

In [35]:
group = grouped_matches.get_group("Barcelona").sort_values("date")

In [36]:
def rolling_averages(group, cols, new_cols):
    group = group.sort_values("date")
    rolling_stats = group[cols].rolling(3, closed='left').mean()
    group[new_cols] = rolling_stats
    group = group.dropna(subset=new_cols)
    return group

In [37]:
cols = ["gf", "ga", "sh", "sot", "dist", "fk", "pk", "pkatt"]
new_cols = [f"{c}_rolling" for c in cols]

rolling_averages(group, cols, new_cols)

,date,time,round,day,venue,result,gf,ga,opponent,xg,...,hour,day_code,gf_rolling,ga_rolling,sh_rolling,sot_rolling,dist_rolling,fk_rolling,pk_rolling,pkatt_rolling
3,2019-09-14,21:00,Matchweek 4,Sat,Home,W,5.0,2.0,Valencia,2.4,...,21,5,2.333333,1.666667,13.000000,4.333333,16.500000,0.000000,0.0,0.000000
5,2019-09-21,21:00,Matchweek 5,Sat,Away,L,0.0,2.0,Granada,0.5,...,21,5,4.000000,2.000000,15.000000,7.000000,18.633333,0.000000,0.0,0.000000
6,2019-09-24,21:00,Matchweek 6,Tue,Home,W,2.0,1.0,Villarreal,0.5,...,21,1,2.333333,2.000000,11.000000,5.000000,20.366667,0.666667,0.0,0.000000
7,2019-09-28,16:00,Matchweek 7,Sat,Away,W,2.0,0.0,Getafe,1.3,...,16,5,2.333333,1.666667,11.000000,5.000000,19.100000,1.000000,0.0,0.000000
9,2019-10-06,21:00,Matchweek 8,Sun,Home,W,4.0,0.0,Sevilla,2.1,...,21,6,1.333333,1.000000,8.666667,3.666667,18.900000,1.000000,0.0,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16,2022-10-29,21:00,Matchweek 12,Sat,Away,W,1.0,0.0,Valencia,1.6,...,21,5,2.666667,1.000000,14.666667,5.666667,14.366667,0.666667,0.0,0.000000
18,2022-11-05,21:00,Matchweek 13,Sat,Home,W,2.0,0.0,Almería,4.0,...,21,5,2.666667,0.000000,13.000000,4.666667,13.966667,0.333333,0.0,0.000000
19,2022-11-08,21:30,Matchweek 14,Tue,Away,W,2.0,1.0,Osasuna,0.8,...,21,1,2.333333,0.000000,16.333333,7.000000,14.266667,0.000000,0.0,0.333333
20,2022-12-31,14:00,Matchweek 15,Sat,Home,D,1.0,1.0,Espanyol,2.2,...,14,5,1.666667,0.333333,16.000000,5.666667,15.166667,0.000000,0.0,0.333333
22,2023-01-08,21:00,Matchweek 16,Sun,Away,W,1.0,0.0,Atlético Madrid,0.7,...,21,6,1.666667,0.666667,18.666667,7.000000,14.800000,0.000000,0.0,0.333333

In [38]:
matches_rolling = matches.groupby("team").apply(lambda x: rolling_averages(x, cols, new_cols))

In [39]:
matches_rolling

                    date   time         round  day venue result   gf   ga  \
team
Alaves     3  2019-09-15  14:00   Matchweek 4  Sun  Home      L  0.0  1.0
           4  2019-09-22  18:30   Matchweek 5  Sun  Away      L  0.0  2.0
           5  2019-09-26  21:00   Matchweek 6  Thu  Away      L  0.0  3.0
           6  2019-09-29  16:00   Matchweek 7  Sun  Home      W  2.0  0.0
           7  2019-10-05  18:30   Matchweek 8  Sat  Away      L  1.0  2.0
...                  ...    ...           ...  ...   ...    ...  ...  ...
Villarreal 20 2022-11-06  18:30  Matchweek 13  Sun  Home      L  0.0  2.0
           21 2022-11-09  20:00  Matchweek 14  Wed  Away      W  1.0  0.0
           24 2022-12-31  16:15  Matchweek 15  Sat  Home      W  2.0  1.0
           26 2023-01-07  16:15  Matchweek 16  Sat  Home      W  2.0  1.0
           27 2023-01-13  21:00  Matchweek 17  Fri  Away      D  1.0  1.0

                    opponent   xg  ...  hour  day_code  gf_rolling ga_rolling  \
team                               ...
Alaves     3         Sevilla  0.8  ...    14         6    0.666667   0.333333
           4   Athletic Club  0.2  ...    18         6    0.333333   0.666667
           5   Real Sociedad  0.3  ...    21         3    0.333333   1.333333
           6        Mallorca  2.1  ...    16         6    0.000000   2.000000
           7        Valencia  1.7  ...    18         5    0.666667   1.666667
...                      ...  ...  ...   ...       ...         ...        ...
Villarreal 20       Mallorca  0.5  ...    18         6    0.666667   1.666667
           21       Espanyol  0.7  ...    20         2    0.666667   1.333333
           24       Valencia  2.5  ...    16         5    0.333333   1.000000
           26    Real Madrid  3.0  ...    16         5    1.000000   1.000000
           27     Celta Vigo  0.1  ...    21         4    1.666667   0.666667

              sh_rolling sot_rolling dist_rolling  fk_rolling  pk_rolling  \
team
Alaves     3    8.000000    1.666667    15.100000    0.333333    0.000000
           4    7.333333    1.000000    14.733333    0.000000    0.000000
           5    5.333333    0.666667    15.433333    0.000000    0.000000
           6    5.333333    0.333333    16.900000    0.000000    0.000000
           7    6.333333    2.000000    18.700000    0.000000    0.333333
...                  ...         ...          ...         ...         ...
Villarreal 20   7.333333    3.000000    19.933333    0.000000    0.000000
           21   8.666667    3.333333    20.133333    0.333333    0.000000
           24   8.333333    2.666667    19.600000    0.333333    0.000000
           26  11.000000    4.333333    19.133333    0.333333    0.000000
           27  13.333333    5.000000    18.166667    0.000000    0.333333

               pkatt_rolling
team
Alaves     3        0.000000
           4        0.000000
           5        0.000000
           6        0.000000
           7        0.333333
...                      ...
Villarreal 20       0.000000
           21       0.000000
           24       0.000000
           26       0.000000
           27       0.333333

[2515 rows x 38 columns]

In [40]:
matches_rolling = matches_rolling.droplevel('team')

In [41]:
matches_rolling

,date,time,round,day,venue,result,gf,ga,opponent,xg,...,hour,day_code,gf_rolling,ga_rolling,sh_rolling,sot_rolling,dist_rolling,fk_rolling,pk_rolling,pkatt_rolling
3,2019-09-15,14:00,Matchweek 4,Sun,Home,L,0.0,1.0,Sevilla,0.8,...,14,6,0.666667,0.333333,8.000000,1.666667,15.100000,0.333333,0.000000,0.000000
4,2019-09-22,18:30,Matchweek 5,Sun,Away,L,0.0,2.0,Athletic Club,0.2,...,18,6,0.333333,0.666667,7.333333,1.000000,14.733333,0.000000,0.000000,0.000000
5,2019-09-26,21:00,Matchweek 6,Thu,Away,L,0.0,3.0,Real Sociedad,0.3,...,21,3,0.333333,1.333333,5.333333,0.666667,15.433333,0.000000,0.000000,0.000000
6,2019-09-29,16:00,Matchweek 7,Sun,Home,W,2.0,0.0,Mallorca,2.1,...,16,6,0.000000,2.000000,5.333333,0.333333,16.900000,0.000000,0.000000,0.000000
7,2019-10-05,18:30,Matchweek 8,Sat,Away,L,1.0,2.0,Valencia,1.7,...,18,5,0.666667,1.666667,6.333333,2.000000,18.700000,0.000000,0.333333,0.333333
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20,2022-11-06,18:30,Matchweek 13,Sun,Home,L,0.0,2.0,Mallorca,0.5,...,18,6,0.666667,1.666667,7.333333,3.000000,19.933333,0.000000,0.000000,0.000000
21,2022-11-09,20:00,Matchweek 14,Wed,Away,W,1.0,0.0,Espanyol,0.7,...,20,2,0.666667,1.333333,8.666667,3.333333,20.133333,0.333333,0.000000,0.000000
24,2022-12-31,16:15,Matchweek 15,Sat,Home,W,2.0,1.0,Valencia,2.5,...,16,5,0.333333,1.000000,8.333333,2.666667,19.600000,0.333333,0.000000,0.000000
26,2023-01-07,16:15,Matchweek 16,Sat,Home,W,2.0,1.0,Real Madrid,3.0,...,16,5,1.000000,1.000000,11.000000,4.333333,19.133333,0.333333,0.000000,0.000000
27,2023-01-13,21:00,Matchweek 17,Fri,Away,D,1.0,1.0,Celta Vigo,0.1,...,21,4,1.666667,0.666667,13.333333,5.000000,18.166667,0.000000,0.333333,0.333333

In [42]:
matches_rolling.index = range(matches_rolling.shape[0])

In [43]:
def make_predictions(data, predictors):
    train = data[data["date"] < '2022-01-01']
    test = data[data["date"] > '2022-01-01']
    rf.fit(train[predictors], train["target"])
    preds = rf.predict(test[predictors])
    combined = pd.DataFrame(dict(actual=test["target"], predicted=preds), index=test.index)
    error = precision_score(test["target"], preds)
    return combined, error

In [44]:
combined, error = make_predictions(matches_rolling, predictors + new_cols)

In [45]:
error

0.5263157894736842

In [46]:
combined = combined.merge(matches_rolling[["date", "team", "opponent", "result"]], left_index=True, right_index=True)

In [47]:
combined.head(10)

     actual  predicted       date    team       opponent result
91        0          0 2022-01-02  Alaves  Real Sociedad      D
92        0          0 2022-01-09  Alaves  Athletic Club      D
93        0          0 2022-01-18  Alaves          Betis      L
94        0          0 2022-01-23  Alaves      Barcelona      L
95        0          0 2022-02-05  Alaves          Elche      L
96        1          0 2022-02-13  Alaves       Valencia      W
97        0          0 2022-02-19  Alaves    Real Madrid      L
98        0          0 2022-02-26  Alaves         Getafe      D
99        0          0 2022-03-04  Alaves        Sevilla      D
100       0          0 2022-03-13  Alaves  Real Sociedad      L

In [48]:
class MissingDict(dict):
    __missing__ = lambda self, key: key

map_values = {"Brighton and Hove Albion": "Brighton", "Manchester United": "Manchester Utd", "Newcastle United": "Newcastle Utd", "Tottenham Hotspur": "Tottenham", "West Ham United": "West Ham", "Wolverhampton Wanderers": "Wolves"} 
mapping = MissingDict(**map_values)

In [49]:
combined["new_team"] = combined["team"].map(mapping)

In [50]:
merged = combined.merge(combined, left_on=["date", "new_team"], right_on=["date", "opponent"])

In [51]:
merged

,actual_x,predicted_x,date,team_x,opponent_x,result_x,new_team_x,actual_y,predicted_y,team_y,opponent_y,result_y,new_team_y
0,1,0,2022-01-03,Athletic Club,Osasuna,W,Athletic Club,0,0,Osasuna,Athletic Club,L,Osasuna
1,0,1,2022-01-09,Athletic Club,Alavés,D,Athletic Club,0,0,Alaves,Athletic Club,D,Alaves
2,1,0,2022-01-23,Athletic Club,Rayo Vallecano,W,Athletic Club,0,0,Rayo Vallecano,Athletic Club,L,Rayo Vallecano
3,1,1,2022-02-07,Athletic Club,Espanyol,W,Athletic Club,0,0,Espanyol,Athletic Club,L,Espanyol
4,0,0,2022-02-14,Athletic Club,Mallorca,L,Athletic Club,1,0,Mallorca,Athletic Club,W,Mallorca
...,...,...,...,...,...,...,...,...,...,...,...,...,...
537,0,0,2022-11-06,Villarreal,Mallorca,L,Villarreal,1,0,Mallorca,Villarreal,W,Mallorca
538,1,0,2022-11-09,Villarreal,Espanyol,W,Villarreal,0,0,Espanyol,Villarreal,L,Espanyol
539,1,0,2022-12-31,Villarreal,Valencia,W,Villarreal,0,0,Valencia,Villarreal,L,Valencia
540,1,0,2023-01-07,Villarreal,Real Madrid,W,Villarreal,0,0,Real Madrid,Villarreal,L,Real Madrid
541,0,0,2023-01-13,Villarreal,Celta Vigo,D,Villarreal,0,0,Celta Vigo,Villarreal,D,Celta Vigo

In [52]:
merged[(merged["predicted_x"] == 1) & (merged["predicted_y"] ==0)]["actual_x"].value_counts()

0    55
1    55
Name: actual_x, dtype: int64